export const gameCards: any = {
  lawsOfPhysicsCards: [
    {
      id: 1,
      name: "Thermal Fluctuation Limit",
      affects: ["Superconducting Qubits", "Superfluid Helium Qubits"],
      effect: "Operational temperatures cannot be maintained reliably."
    },
    {
      id: 2,
      name: "Quantum Decoherence Limit",
      affects: ["Trapped Ion Qubits", "Silicon Spin Qubits"],
      effect: "Coherence times are too short for practical computation."
    },
    {
      id: 3,
      name: "Photon Loss Limit",
      affects: ["Photonic Qubits"],
      effect: "Photons are lost during transmission, breaking entanglement."
    },
    {
      id: 4,
      name: "Non-Abelian Particle Absence",
      affects: ["Topological Qubits"],
      effect: "Necessary particles do not exist or cannot be utilized."
    },
    {
      id: 5,
      name: "Spin Coherence Limit",
      affects: ["Silicon Spin Qubits"],
      effect: "Spin states decohere too rapidly."
    },
    {
      id: 6,
      name: "Atomic Interaction Limit",
      affects: ["Neutral Atom Qubits"],
      effect: "Uncontrollable atomic interactions prevent scalability."
    },
    {
      id: 7,
      name: "Vacancy Defect Limit",
      affects: ["Diamond Vacancy Qubits"],
      effect: "Cannot create stable vacancies at scale."
    },
    {
      id: 8,
      name: "Superfluid Instability",
      affects: ["Superfluid Helium Qubits"],
      effect: "Superfluid states are disrupted by unknown factors."
    }
  ],

  corporateIdentityCards: [
    {
      id: "CI5",
      name: "Quantum Horizons Ltd.",
      type: "CI",
      corporateCulture: "Stealth Innovators",
      startingEmployees: 2,
      startingAgents: 2,
      startingTokens: { "Secret Tech Token": 1 },
      uniqueAbility1: {
        name: "Hidden Research",
        mechanicsType: ["GA", "PR"],
        description: "Once per round, perform a Research Physics action without revealing it to other players"
      },
      uniqueAbility2: {
        name: "Cloaked Operations",
        mechanicsType: "MM",
        description: "In Phase 2, your actions are hidden unless they directly affect another player"
      },
      description: "Quantum Horizons Ltd. specializes in covert operations and secretive research. Their stealth approach allows them to gather information and prepare for Phase 2 without drawing attention."
    },
    {
      id: "CI6",
      name: "EnlightenTech Corp.",
      type: "CI",
      corporateCulture: "Philanthropic Visionaries",
      startingEmployees: 3,
      startingAgents: 1,
      startingTokens: { "Public Influence Token": 1 },
      uniqueAbility1: {
        name: "Open Source Initiative",
        mechanicsType: "RA",
        description: "When you perform Upgrade Entanglement, you may allow all players to benefit, gaining Influence Points in return"
      },
      uniqueAbility2: {
        name: "Global Support",
        mechanicsType: "RA",
        description: "In Phase 2, start with additional Influence Points based on your Public Influence Tokens"
      },
      description: "EnlightenTech Corp. believes in the collective advancement of technology. By sharing advancements, they gain public support for Phase 2."
    },
    {
      id: "CI7",
      name: "Chrono Dynamics",
      type: "CI",
      corporateCulture: "Temporal Pioneers",
      startingEmployees: 2,
      startingAgents: 1,
      startingTokens: { "Time Manipulation Token": 1 },
      uniqueAbility1: {
        name: "Quantum Tunneling",
        mechanicsType: "GA",
        description: "Once per game in Phase 1, take an extra turn immediately after your current turn"
      },
      uniqueAbility2: {
        name: "Temporal Advantage",
        mechanicsType: "CT",
        description: "In Phase 2, manipulate turn order once per round"
      },
      description: "Chrono Dynamics explores quantum time manipulation, providing unique strategic advantages."
    },
    {
      id: "CI8",
      name: "CyberCore Industries",
      type: "CI",
      corporateCulture: "Cybernetic Integrators",
      startingEmployees: 3,
      startingAgents: 1,
      startingTokens: { "Cyber Upgrade Token": 1 },
      uniqueAbility1: {
        name: "Cybernetic Enhancements",
        mechanicsType: "GA",
        description: "Once per round, an Employee can perform two actions instead of one"
      },
      uniqueAbility2: {
        name: "AI Integration",
        mechanicsType: "MM",
        description: "In Phase 2, Agents can act as Directors for one action per round"
      },
      description: "CyberCore Industries merges cybernetics with quantum computing, enhancing workforce efficiency."
    },
    {
      id: "CI9",
      name: "MetaMorph Labs",
      type: "CI",
      corporateCulture: "Adaptive Morphologists",
      startingEmployees: 2,
      startingAgents: 1,
      startingTokens: { "Morph Token": 1 },
      uniqueAbility1: {
        name: "Technology Morphing",
        mechanicsType: "MM",
        description: "Once during Phase 1, swap your Design Type with an unclaimed one"
      },
      uniqueAbility2: {
        name: "Adaptive Strategies",
        mechanicsType: "MM",
        description: "In Phase 2, change one of your Special Abilities at the start of each round"
      },
      description: "MetaMorph Labs excels in adapting technology and strategies to the evolving landscape."
    },
    {
      id: "CI10",
      name: "Equinox Enterprises",
      type: "CI",
      corporateCulture: "Phase 2 Strategists",
      startingEmployees: 2,
      startingAgents: 2,
      startingTokens: { "Early Warning Token": 1 },
      uniqueAbility1: {
        name: "Phase 2 Preparation",
        mechanicsType: "PR",
        description: "Gain ability to look at one additional Laws of Physics card during Research Physics"
      },
      uniqueAbility2: {
        name: "Counter Supremacy",
        mechanicsType: ["GA", "MT"],
        description: "In Phase 2, start with one Espionage action already completed"
      },
      description: "Equinox Enterprises focuses on long-term strategies, preparing meticulously for Phase 2."
    },
    {
      id: "CI11",
      name: "OmniSphere Global",
      type: "CI",
      corporateCulture: "Monopolistic Visionaries",
      startingEmployees: 4,
      startingAgents: 1,
      startingTokens: {},
      uniqueAbility1: {
        name: "Resource Accumulation",
        mechanicsType: "RA",
        description: "Gain an extra resource whenever you perform an action that grants resources"
      },
      uniqueAbility2: {
        name: "Market Dominance",
        mechanicsType: "RA",
        description: "In Phase 2, your Influence Points are doubled"
      },
      description: "OmniSphere Global aims for total market control by aggressively accumulating resources."
    },
    {
      id: "CI12",
      name: "ShadowTech Syndicate",
      type: "CI",
      corporateCulture: "Covert Saboteurs",
      startingEmployees: 1,
      startingAgents: 3,
      startingTokens: {},
      uniqueAbility1: {
        name: "Espionage Mastery",
        mechanicsType: "MM",
        description: "Agents can perform Employee actions involving information gathering"
      },
      uniqueAbility2: {
        name: "Sabotage Specialists",
        mechanicsType: "AO",
        description: "In Phase 2, your sabotage actions are more effective"
      },
      description: "ShadowTech Syndicate focuses on espionage and sabotage to undermine competitors."
    },
    {
      id: "CI13",
      name: "GaiaTech Solutions",
      type: "CI",
      corporateCulture: "Eco-Conscious Developers",
      startingEmployees: 3,
      startingAgents: 1,
      startingTokens: { "Sustainability Token": 1 },
      uniqueAbility1: {
        name: "Green Innovation",
        mechanicsType: "MT",
        description: "When performing Isolation or Correction, you may remove an Interference Cube from another player's board, gaining Influence Points"
      },
      uniqueAbility2: {
        name: "Planetary Protection",
        mechanicsType: "DN",
        description: "In Phase 2, prevent the 'everyone loses' outcome once"
      },
      description: "GaiaTech Solutions ensures technological advancement doesn't harm the environment."
    },
    {
      id: "CI14",
      name: "Infinity Loop Inc.",
      type: "CI",
      corporateCulture: "Theoretical Explorers",
      startingEmployees: 2,
      startingAgents: 1,
      startingTokens: { "Theoretical Insight Token": 1 },
      uniqueAbility1: {
        name: "Advanced Theories",
        mechanicsType: "MM",
        description: "Once per round, re-roll or adjust the outcome of any random element"
      },
      uniqueAbility2: {
        name: "Multiverse Manipulation",
        mechanicsType: "MM",
        description: "In Phase 2, introduce a new Laws of Physics card into play"
      },
      description: "Infinity Loop Inc. leverages theoretical physics to gain unexpected advantages."
    },
    {
      id: "CI15",
      name: "Titan Forge Systems",
      type: "CI",
      corporateCulture: "Industrial Powerhouses",
      startingEmployees: 5,
      startingAgents: 0,
      startingTokens: {},
      uniqueAbility1: {
        name: "Mass Production",
        mechanicsType: "MT",
        description: "When performing Qubits action, place an extra Qubit Token"
      },
      uniqueAbility2: {
        name: "Late Game Surge",
        mechanicsType: "RA",
        description: "In Phase 2, gain 2 Agents to deploy"
      },
      description: "Titan Forge Systems relies on production capacity, becoming formidable in the endgame."
    },
    {
      id: "CI16",
      name: "Nexus AI",
      type: "CI",
      corporateCulture: "AI-Driven Strategists",
      startingEmployees: 2,
      startingAgents: 1,
      startingTokens: { "AI Algorithm Token": 1 },
      uniqueAbility1: {
        name: "Predictive Modeling",
        mechanicsType: "PR",
        description: "Once per round, predict another player's action; if correct, gain a bonus action"
      },
      uniqueAbility2: {
        name: "Autonomous Agents",
        mechanicsType: "DN",
        description: "In Phase 2, Agents can act independently, performing actions even when affected by opponents"
      },
      description: "Nexus AI integrates artificial intelligence into decision-making processes."
    },
    {
      id: "CI17",
      name: "Aurora Biotechnics",
      type: "CI",
      corporateCulture: "Quantum Biologists",
      startingEmployees: 3,
      startingAgents: 1,
      startingTokens: { "Bio-Quantum Token": 1 },
      uniqueAbility1: {
        name: "Organic Qubits",
        mechanicsType: "MT",
        description: "Use Bio-Qubits instead of Qubits, less susceptible to certain Laws of Physics"
      },
      uniqueAbility2: {
        name: "Symbiotic Networks",
        mechanicsType: "MM",
        description: "In Phase 2, form symbiotic alliances, sharing benefits without formal agreements"
      },
      description: "Aurora Biotechnics combines biology with quantum computing."
    },
    {
      id: "CI18",
      name: "Paradox Interactive Tech.",
      type: "CI",
      corporateCulture: "Reality Manipulators",
      startingEmployees: 2,
      startingAgents: 2,
      startingTokens: { "Paradox Token": 1 },
      uniqueAbility1: {
        name: "Reality Shift",
        mechanicsType: "MM",
        description: "Once per game in Phase 1, swap positions with another player on the development track"
      },
      uniqueAbility2: {
        name: "Dimensional Rift",
        mechanicsType: "DN",
        description: "In Phase 2, negate one player's action entirely once per round"
      },
      description: "Paradox Interactive explores boundaries between dimensions to gain an edge."
    },
    {
      id: "CI19",
      name: "Solaris Fusion Corp.",
      type: "CI",
      corporateCulture: "Energy Innovators",
      startingEmployees: 3,
      startingAgents: 1,
      startingTokens: { "Energy Resource Token": 1 },
      uniqueAbility1: {
        name: "Fusion Energy",
        mechanicsType: "RA",
        description: "Once per round, use unique energy resource to replace any standard resource"
      },
      uniqueAbility2: {
        name: "Power Surge",
        mechanicsType: "AO",
        description: "In Phase 2, disable all other players' resources for one round"
      },
      description: "Solaris Fusion Corp. harnesses fusion energy for resource flexibility."
    },
    {
      id: "CI20",
      name: "Celestial Mechanics",
      type: "CI",
      corporateCulture: "Space-Based Strategists",
      startingEmployees: 2,
      startingAgents: 1,
      startingTokens: { "Orbital Platform Token": 1 },
      uniqueAbility1: {
        name: "Orbital Advantage",
        mechanicsType: "DN",
        description: "Technologies immune to Laws of Physics related to environmental decoherence"
      },
      uniqueAbility2: {
        name: "Satellite Network",
        mechanicsType: "AO",
        description: "In Phase 2, perform actions affecting any player regardless of limitations"
      },
      description: "Celestial Mechanics operates in space, bypassing terrestrial limitations."
    }
  ],

  strategyCards: [
    {
      id: "SC1",
      name: "Grant Funding",
      type: "SC1",
      category: "Research Enhancement",
      mechanicsType: "RA",
      mechanicsVariables: "+1 Resource",
      coopChange: 0,
      innovChange: 1,
      canBeHired: true,
      description: "Gain one additional resource to use this round. Accelerates research. (+Innov)"
    },
    {
      id: "SC2",
      name: "Market Diversion",
      type: "SC1",
      category: "Corporate Maneuver",
      mechanicsType: "AO",
      mechanicsVariables: "-1 Emp Action",
      coopChange: -1,
      innovChange: -1,
      canBeHired: true,
      description: "Target player loses one Employee action next round. Hinders progress. (-Coop, -Innov)"
    },
    {
      id: "SC3",
      name: "Patent Filing",
      type: "SC1",
      category: "Regulatory Action",
      mechanicsType: "MM",
      mechanicsVariables: "Patent Token",
      coopChange: -1,
      innovChange: 0,
      canBeHired: true,
      description: "Place a Patent Token on a technology; others must pay one resource to use related actions. Controls technology. (-Coop)"
    },
    {
      id: "SC4",
      name: "Minor Sabotage",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "MT",
      mechanicsVariables: "+1 Interf Cube",
      coopChange: -2,
      innovChange: -1,
      canBeHired: true,
      description: "Add one Interference Cube to a target's board. Slows development. (-Coop, -Innov)"
    },
    {
      id: "SC5",
      name: "Cybersecurity Upgrade",
      type: "SC1",
      category: "Defensive Measure",
      mechanicsType: "DN",
      mechanicsVariables: "Negate Sabotage",
      coopChange: 0,
      innovChange: 0,
      canBeHired: true,
      description: "Negate the next Sabotage card played against you. Protects assets."
    },
    {
      id: "SC6",
      name: "Collaborative Conference",
      type: "SC1",
      category: "Research Enhancement",
      mechanicsType: "DC",
      mechanicsVariables: "Draw Cards",
      coopChange: 2,
      innovChange: 1,
      canBeHired: true,
      description: "All players draw one Strategy Card; you draw two. Promotes collaboration. (+Coop, +Innov)"
    },
    {
      id: "SC7",
      name: "Regulatory Lobbying",
      type: "SC1",
      category: "Regulatory Action",
      mechanicsType: "MM",
      mechanicsVariables: "Regulation Token",
      coopChange: -1,
      innovChange: 0,
      canBeHired: true,
      description: "Place a Regulation Token on a location; actions there cost an extra resource. Controls locations. (-Coop)"
    },
    {
      id: "SC8",
      name: "Efficiency Boost",
      type: "SC1",
      category: "Corporate Maneuver",
      mechanicsType: "GA",
      mechanicsVariables: "+1 Emp Action",
      coopChange: 0,
      innovChange: 0,
      canBeHired: true,
      description: "Perform an additional Employee action this round. Increases productivity."
    },
    {
      id: "SC9",
      name: "Espionage Probe",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "PR",
      mechanicsVariables: "Peek Hand",
      coopChange: -1,
      innovChange: -1,
      canBeHired: true,
      description: "Look at another player's Strategy Cards. Gains insight. (-Coop, -Innov)"
    },
    {
      id: "SC10",
      name: "Error Correction Breakthrough",
      type: "SC1",
      category: "Research Enhancement",
      mechanicsType: "MT",
      mechanicsVariables: "-2 Interf Cubes",
      coopChange: 0,
      innovChange: 2,
      canBeHired: true,
      description: "Remove up to two Interference Cubes from your board. Reduces errors. (+Innov)"
    },
    {
      id: "SC11",
      name: "Resource Optimization",
      type: "SC1",
      category: "Corporate Maneuver",
      mechanicsType: "RA",
      mechanicsVariables: "-1 Resource Cost",
      coopChange: 0,
      innovChange: 1,
      canBeHired: true,
      description: "Reduce the cost of your next action by one resource. Enhances efficiency. (+Innov)"
    },
    {
      id: "SC12",
      name: "Industrial Espionage",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Steal Resource",
      coopChange: -2,
      innovChange: -1,
      canBeHired: true,
      description: "Steal one resource from a target player. Increases yours. (-Coop, -Innov)"
    },
    {
      id: "SC13",
      name: "Strategic Alliance",
      type: "SC1",
      category: "Alliance Building",
      mechanicsType: "MM",
      mechanicsVariables: "Share Action",
      coopChange: 2,
      innovChange: 0,
      canBeHired: true,
      description: "Choose a player; you both perform an extra action this round. Fosters cooperation. (+Coop)"
    },
    {
      id: "SC14",
      name: "Quantum Insight",
      type: "SC1",
      category: "Research Enhancement",
      mechanicsType: "PR",
      mechanicsVariables: "Peek Laws",
      coopChange: 0,
      innovChange: 2,
      canBeHired: true,
      description: "Look at an additional Laws of Physics card. Increases knowledge. (+Innov)"
    },
    {
      id: "SC15",
      name: "Defensive Protocols",
      type: "SC1",
      category: "Defensive Measure",
      mechanicsType: "DN",
      mechanicsVariables: "Block AO",
      coopChange: 0,
      innovChange: 0,
      canBeHired: true,
      description: "Prevent an opponent from affecting you with an AO card this round. Shields operations."
    },
    {
      id: "SC16",
      name: "Public Relations Campaign",
      type: "SC1",
      category: "Corporate Maneuver",
      mechanicsType: "RA",
      mechanicsVariables: "+1 Influence",
      coopChange: 1,
      innovChange: 0,
      canBeHired: true,
      description: "Gain one Influence Point. Improves image. (+Coop)"
    },
    {
      id: "SC17",
      name: "Data Breach",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Discard Card",
      coopChange: -2,
      innovChange: -1,
      canBeHired: true,
      description: "Target player discards one random Strategy Card. Disrupts plans. (-Coop, -Innov)"
    },
    {
      id: "SC18",
      name: "Accelerated Development",
      type: "SC1",
      category: "Research Enhancement",
      mechanicsType: "GA",
      mechanicsVariables: "Immediate Action",
      coopChange: 0,
      innovChange: 1,
      canBeHired: true,
      description: "Immediately perform a second action. Speeds progress. (+Innov)"
    },
    {
      id: "SC19",
      name: "Supply Chain Disruption",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "+1 Resource Cost",
      coopChange: -1,
      innovChange: -1,
      canBeHired: true,
      description: "Target player's next action costs one extra resource. Hinders efficiency. (-Coop, -Innov)"
    },
    {
      id: "SC20",
      name: "Innovation Award",
      type: "SC1",
      category: "Research Enhancement",
      mechanicsType: "RA",
      mechanicsVariables: "+2 Resources",
      coopChange: 1,
      innovChange: 2,
      canBeHired: true,
      description: "Gain two resources if you performed Research Physics this round. Rewards innovation. (+Coop, +Innov)"
    },
    {
      id: "SC21",
      name: "Secure Communications",
      type: "SC1",
      category: "Defensive Measure",
      mechanicsType: "DN",
      mechanicsVariables: "Protect PR",
      coopChange: 0,
      innovChange: 0,
      canBeHired: true,
      description: "Prevent others from peeking at your info this round. Maintains secrecy."
    },
    {
      id: "SC22",
      name: "Hostile Takeover",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Control Asset",
      coopChange: -2,
      innovChange: -2,
      canBeHired: true,
      description: "Take control of a target player's asset for one round. Redirects benefits. (-Coop, -Innov)"
    },
    {
      id: "SC23",
      name: "Market Expansion",
      type: "SC1",
      category: "Corporate Maneuver",
      mechanicsType: "RA",
      mechanicsVariables: "+1 Resource",
      coopChange: 0,
      innovChange: 1,
      canBeHired: true,
      description: "Gain one resource for each unique technology you control. Encourages diversity. (+Innov)"
    },
    {
      id: "SC24",
      name: "Trade Secret",
      type: "SC1",
      category: "Defensive Measure",
      mechanicsType: "DN",
      mechanicsVariables: "Negate PR",
      coopChange: 0,
      innovChange: 0,
      canBeHired: true,
      description: "Negate a Peek/Reveal action targeting you. Protects info."
    },
    {
      id: "SC25",
      name: "Resource Exploitation",
      type: "SC1",
      category: "Corporate Maneuver",
      mechanicsType: ["RA", "ET"],
      mechanicsVariables: "+2 Resources, +1 Arms Race",
      coopChange: -2,
      innovChange: -2,
      canBeHired: true,
      description: "Gain two resources but increase Arms Race Track by 1. High-risk gain. (-Coop, -Innov)"
    },
    {
      id: "SC26",
      name: "Technical Glitch",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "MT",
      mechanicsVariables: "+1 Interf Cube",
      coopChange: -1,
      innovChange: -1,
      canBeHired: true,
      description: "Add one Interference Cube to a target's Tolerance track. Increases errors. (-Coop, -Innov)"
    },
    {
      id: "SC27",
      name: "Employee Training",
      type: "SC1",
      category: "Research Enhancement",
      mechanicsType: "GA",
      mechanicsVariables: "+1 Emp Ability",
      coopChange: 0,
      innovChange: 1,
      canBeHired: true,
      description: "One Employee gains an extra ability this round. Enhances workforce. (+Innov)"
    },
    {
      id: "SC28",
      name: "Patent Infringement",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Disable Patent",
      coopChange: -1,
      innovChange: -1,
      canBeHired: true,
      description: "Negate effect of a Patent Token for one round. Bypasses restrictions. (-Coop, -Innov)"
    },
    {
      id: "SC29",
      name: "Regulatory Compliance",
      type: "SC1",
      category: "Regulatory Action",
      mechanicsType: "RA",
      mechanicsVariables: "-1 Resource Cost",
      coopChange: 0,
      innovChange: 0,
      canBeHired: true,
      description: "Reduce costs when acting under a Regulation Token. Benefits compliance."
    },
    {
      id: "SC30",
      name: "Information Exchange",
      type: "SC1",
      category: "Alliance Building",
      mechanicsType: "DC",
      mechanicsVariables: "Swap Cards",
      coopChange: 1,
      innovChange: 1,
      canBeHired: true,
      description: "Trade one Strategy Card with another player. Encourages cooperation. (+Coop, +Innov)"
    },
    {
      id: "SC31",
      name: "Media Leak",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "-1 Influence",
      coopChange: -2,
      innovChange: 0,
      canBeHired: true,
      description: "Target player loses one Influence Point. Damages reputation. (-Coop)"
    },
    {
      id: "SC32",
      name: "Quantum Leap",
      type: "SC1",
      category: "Research Enhancement",
      mechanicsType: "MT",
      mechanicsVariables: "+1 Qubit",
      coopChange: 0,
      innovChange: 2,
      canBeHired: true,
      description: "Add one Qubit Token to your board. Advances development. (+Innov)"
    },
    {
      id: "SC33",
      name: "Staff Reassignment",
      type: "SC1",
      category: "Corporate Maneuver",
      mechanicsType: "GA",
      mechanicsVariables: "Reassign Pawn",
      coopChange: 0,
      innovChange: 0,
      canBeHired: true,
      description: "Move one pawn to a different action space. Increases flexibility."
    },
    {
      id: "SC34",
      name: "Defensive Network",
      type: "SC1",
      category: "Defensive Measure",
      mechanicsType: "DN",
      mechanicsVariables: "Block MT",
      coopChange: 0,
      innovChange: 0,
      canBeHired: true,
      description: "Prevent an Interference Cube from being added to your board. Protects integrity."
    },
    {
      id: "SC35",
      name: "Black Market Resources",
      type: "SC1",
      category: "Corporate Maneuver",
      mechanicsType: "RA",
      mechanicsVariables: "+1 Resource",
      coopChange: -1,
      innovChange: -2,
      canBeHired: true,
      description: "Gain one resource but risk losing one Influence if exposed. High-risk gain. (-Coop, -Innov)"
    },
    {
      id: "SC36",
      name: "Think Tank Collaboration",
      type: "SC1",
      category: "Research Enhancement",
      mechanicsType: "GA",
      mechanicsVariables: "Shared Action",
      coopChange: 2,
      innovChange: 1,
      canBeHired: true,
      description: "All players perform Research Physics; you gain an extra resource. Shared progress. (+Coop, +Innov)"
    },
    {
      id: "SC37",
      name: "Firewall Upgrade",
      type: "SC1",
      category: "Defensive Measure",
      mechanicsType: "DN",
      mechanicsVariables: "Block AO",
      coopChange: 0,
      innovChange: 0,
      canBeHired: true,
      description: "Block an Affect Opponent action targeting you. Secures operations."
    },
    {
      id: "SC38",
      name: "Disruptive Innovation",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Skip Action",
      coopChange: -3,
      innovChange: -2,
      canBeHired: true,
      description: "Target player skips their next turn. Major disruption. (-Coop, -Innov)"
    },
    {
      id: "SC39",
      name: "Resource Acquisition",
      type: "SC1",
      category: "Corporate Maneuver",
      mechanicsType: "RA",
      mechanicsVariables: "+1 Resource",
      coopChange: 0,
      innovChange: 0,
      canBeHired: true,
      description: "Gain one resource from supply. Increases assets."
    },
    {
      id: "SC40",
      name: "Covert Operation",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Hidden Effect",
      coopChange: -1,
      innovChange: -1,
      canBeHired: true,
      description: "Play face down; reveal to negate an opponent's action. Adds uncertainty. (-Coop, -Innov)"
    },
    {
      id: "SC41",
      name: "Emergency Protocols",
      type: "SC1",
      category: "Defensive Measure",
      mechanicsType: "DN",
      mechanicsVariables: "Immediate Defense",
      coopChange: 0,
      innovChange: 0,
      canBeHired: true,
      description: "Play immediately when targeted to negate effect. Reactive protection."
    },
    {
      id: "SC42",
      name: "Shared Patent",
      type: "SC1",
      category: "Alliance Building",
      mechanicsType: "MM",
      mechanicsVariables: "Shared Tech",
      coopChange: 1,
      innovChange: 1,
      canBeHired: true,
      description: "Create a shared Patent Token; both benefit from reduced costs. Encourages partnership. (+Coop, +Innov)"
    },
    {
      id: "SC43",
      name: "Market Manipulation",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "-1 Resource",
      coopChange: -2,
      innovChange: -1,
      canBeHired: true,
      description: "Target player loses one resource. Weakens position. (-Coop, -Innov)"
    },
    {
      id: "SC44",
      name: "Enhanced Productivity",
      type: "SC1",
      category: "Corporate Maneuver",
      mechanicsType: "GA",
      mechanicsVariables: "+1 Emp Action",
      coopChange: 0,
      innovChange: 1,
      canBeHired: true,
      description: "One Employee performs an extra action this round. Boosts efficiency. (+Innov)"
    },
    {
      id: "SC45",
      name: "Regulatory Evasion",
      type: "SC1",
      category: "Corporate Maneuver",
      mechanicsType: "MM",
      mechanicsVariables: "Ignore Regulation",
      coopChange: -1,
      innovChange: -1,
      canBeHired: true,
      description: "Ignore effects of one Regulation Token this round. Circumvents constraints. (-Coop, -Innov)"
    },
    {
      id: "SC46",
      name: "Data Analysis",
      type: "SC1",
      category: "Research Enhancement",
      mechanicsType: "PR",
      mechanicsVariables: "Peek Deck",
      coopChange: 0,
      innovChange: 1,
      canBeHired: true,
      description: "Look at top three Strategy Cards; rearrange them. Plans ahead. (+Innov)"
    },
    {
      id: "SC47",
      name: "Competitive Edge",
      type: "SC1",
      category: "Corporate Maneuver",
      mechanicsType: "RA",
      mechanicsVariables: "+1 Resource",
      coopChange: 0,
      innovChange: 1,
      canBeHired: true,
      description: "Gain one resource if you have more Qubits than others. Rewards leadership. (+Innov)"
    },
    {
      id: "SC48",
      name: "Joint Venture",
      type: "SC1",
      category: "Alliance Building",
      mechanicsType: "MM",
      mechanicsVariables: "Combined Action",
      coopChange: 2,
      innovChange: 1,
      canBeHired: true,
      description: "Perform an action jointly; both gain benefits. Leverages cooperation. (+Coop, +Innov)"
    },
    {
      id: "SC49",
      name: "Targeted Sabotage",
      type: "SC1",
      category: "Sabotage",
      mechanicsType: "MT",
      mechanicsVariables: "+2 Interf Cubes",
      coopChange: -3,
      innovChange: -2,
      canBeHired: true,
      description: "Add two Interference Cubes to a target's board. Significant setback. (-Coop, -Innov)"
    },
    {
      id: "SC50",
      name: "Inspiration Burst",
      type: "SC1",
      category: "Research Enhancement",
      mechanicsType: "DC",
      mechanicsVariables: "Draw Cards",
      coopChange: 0,
      innovChange: 2,
      canBeHired: true,
      description: "Draw two Strategy Cards; discard one. Expands options. (+Innov)"
    },
    {
      id: "SC51",
      name: "Collateral Damage",
      type: "SC1",
      category: "Extreme Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Set Coop to -5",
      coopChange: -5,
      innovChange: 0,
      canBeHired: false,
      description: "Perform a devastating sabotage that sets your Cooperation metric to -5. Major impact. (-Coop)"
    },
    {
      id: "SC52",
      name: "Nuclear Fusion Sabotage",
      type: "SC1",
      category: "Extreme Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Destroy Facility",
      coopChange: -5,
      innovChange: -2,
      canBeHired: false,
      description: "Destroy a target player's facility; they lose two turns. (-Coop, -Innov)"
    },
    {
      id: "SC53",
      name: "Quantum Collapse",
      type: "SC1",
      category: "Extreme Event",
      mechanicsType: "ET",
      mechanicsVariables: "Reset Innov to 0",
      coopChange: 0,
      innovChange: "Set Innov to 0",
      canBeHired: false,
      description: "Reset all players' Innovation metrics to 0. Levels the field."
    },
    {
      id: "SC54",
      name: "Global Hack",
      type: "SC1",
      category: "Extreme Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Discard Hand",
      coopChange: -4,
      innovChange: -3,
      canBeHired: false,
      description: "All opponents discard their Strategy Cards. (-Coop, -Innov)"
    },
    {
      id: "SC55",
      name: "Technological Embargo",
      type: "SC1",
      category: "Extreme Maneuver",
      mechanicsType: "MM",
      mechanicsVariables: "Block Tech",
      coopChange: -3,
      innovChange: -2,
      canBeHired: false,
      description: "Prevent all players from using a specific technology this round. (-Coop, -Innov)"
    },
    {
      id: "SC56",
      name: "Time Paradox",
      type: "SC1",
      category: "Extreme Event",
      mechanicsType: "CT",
      mechanicsVariables: "Reverse Turn Order",
      coopChange: 0,
      innovChange: 0,
      canBeHired: false,
      description: "Reverse the turn order. Unpredictable shift."
    },
    {
      id: "SC57",
      name: "Resource Monopoly",
      type: "SC1",
      category: "Extreme Maneuver",
      mechanicsType: "RA",
      mechanicsVariables: "Gain All Resources",
      coopChange: -5,
      innovChange: -2,
      canBeHired: false,
      description: "Claim all available resources from the supply. (-Coop, -Innov)"
    },
    {
      id: "SC58",
      name: "Quantum Rift",
      type: "SC1",
      category: "Extreme Event",
      mechanicsType: "MM",
      mechanicsVariables: "Swap Boards",
      coopChange: 0,
      innovChange: 0,
      canBeHired: false,
      description: "Swap Quantum Computer Boards with another player. High risk."
    },
    {
      id: "SC59",
      name: "Blackout",
      type: "SC1",
      category: "Extreme Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Skip Next Turn",
      coopChange: -4,
      innovChange: -2,
      canBeHired: false,
      description: "All opponents skip their next turn. (-Coop, -Innov)"
    },
    {
      id: "SC60",
      name: "Ultimate Sacrifice",
      type: "SC1",
      category: "Extreme Maneuver",
      mechanicsType: "RA",
      mechanicsVariables: "Gain 5 Resources",
      coopChange: "Set Coop to 0",
      innovChange: 0,
      canBeHired: false,
      description: "Gain five resources but reset your Cooperation metric to 0. (Resets Coop)"
    },
    {
      id: "SC61",
      name: "Coffee Break",
      type: "SC1",
      category: "Fun Maneuver",
      mechanicsType: "GA",
      mechanicsVariables: "No Effect",
      coopChange: 1,
      innovChange: 0,
      canBeHired: false,
      description: "All players pause for a Coffee Break; you gain an extra action. (+Coop)"
    },
    {
      id: "SC62",
      name: "Birthday Surprise",
      type: "SC1",
      category: "Fun Event",
      mechanicsType: "RA",
      mechanicsVariables: "Gain 1 Resource",
      coopChange: 0,
      innovChange: 0,
      canBeHired: false,
      description: "It's your birthday! Gain one resource. Everyone celebrates."
    },
    {
      id: "SC63",
      name: "Office Party",
      type: "SC1",
      category: "Fun Event",
      mechanicsType: "GA",
      mechanicsVariables: "All Gain Action",
      coopChange: 1,
      innovChange: 0,
      canBeHired: false,
      description: "All players gain an extra Employee action this round. (+Coop)"
    },
    {
      id: "SC64",
      name: "Pizza Delivery",
      type: "SC1",
      category: "Fun Maneuver",
      mechanicsType: "RA",
      mechanicsVariables: "Distribute Resources",
      coopChange: 1,
      innovChange: 0,
      canBeHired: false,
      description: "Share pizza with others; distribute two resources among players. (+Coop)"
    },
    {
      id: "SC65",
      name: "Laughing Gas Leak",
      type: "SC1",
      category: "Fun Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "All Skip Action",
      coopChange: -1,
      innovChange: 0,
      canBeHired: false,
      description: "All players, including you, skip their next Employee action. Laughter ensues. (-Coop)"
    },
    {
      id: "SC66",
      name: "Misplaced Memo",
      type: "SC1",
      category: "Fun Event",
      mechanicsType: "PR",
      mechanicsVariables: "Reveal Top Card",
      coopChange: 0,
      innovChange: 0,
      canBeHired: false,
      description: "Reveal the top Strategy Card; all players see it."
    },
    {
      id: "SC67",
      name: "Cat Video Distraction",
      type: "SC1",
      category: "Fun Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Delay Action",
      coopChange: -1,
      innovChange: 0,
      canBeHired: false,
      description: "Target player is distracted by cat videos; their next action is delayed. (-Coop)"
    },
    {
      id: "SC68",
      name: "Inspirational Poster",
      type: "SC1",
      category: "Fun Enhancement",
      mechanicsType: "RA",
      mechanicsVariables: "+1 Influence",
      coopChange: 1,
      innovChange: 1,
      canBeHired: false,
      description: "Your new poster boosts morale. Gain one Influence Point. (+Coop, +Innov)"
    },
    {
      id: "SC69",
      name: "Unexpected Holiday",
      type: "SC1",
      category: "Fun Event",
      mechanicsType: "GA",
      mechanicsVariables: "No Actions This Round",
      coopChange: 0,
      innovChange: 0,
      canBeHired: false,
      description: "All players take a break; no actions this round. Relaxing!"
    },
    {
      id: "SC70",
      name: "Dance-Off Challenge",
      type: "SC1",
      category: "Fun Maneuver",
      mechanicsType: "GA",
      mechanicsVariables: "Dance-Off",
      coopChange: 1,
      innovChange: 0,
      canBeHired: false,
      description: "Challenge a player to a dance-off; winner gains an extra action. (+Coop)"
    },
    {
      id: "SC71",
      name: "Employee Training Program",
      type: "SC1",
      category: "Hire Upgrade",
      mechanicsType: "MM",
      mechanicsVariables: "Upgrade your hire; its action is more effective",
      coopChange: 1,
      innovChange: 1,
      canBeHired: false,
      description: "Enhance your existing hire. Your hire's action now provides additional benefits."
    },
    {
      id: "SC72",
      name: "Headhunting",
      type: "SC1",
      category: "Hire Interaction",
      mechanicsType: "AO",
      mechanicsVariables: "Attempt to steal another player's hire",
      coopChange: -2,
      innovChange: -1,
      canBeHired: false,
      description: "Target a player's hire and attempt to recruit them to your side. Success is not guaranteed."
    },
    {
      id: "SC73",
      name: "Discredit Consultant",
      type: "SC1",
      category: "Hire Interaction",
      mechanicsType: "AO",
      mechanicsVariables: "Force an opponent to discard their hire",
      coopChange: -1,
      innovChange: 0,
      canBeHired: false,
      description: "Publicly discredit an opponent's hire, removing them from play."
    },
    {
      id: "SC74",
      name: "Security Measures",
      type: "SC1",
      category: "Hire Protection",
      mechanicsType: "DN",
      mechanicsVariables: "Protect your hire from being stolen or discredited",
      coopChange: 0,
      innovChange: 0,
      canBeHired: false,
      description: "Implement security protocols to prevent opponents from targeting your hire."
    },
    {
      id: "SC75",
      name: "Motivational Speaker",
      type: "SC1",
      category: "Hire Upgrade",
      mechanicsType: "MM",
      mechanicsVariables: "Your hire's action grants an additional benefit when used",
      coopChange: 1,
      innovChange: 1,
      canBeHired: false,
      description: "Boost your hire's effectiveness. Gain an extra resource or effect when using your hire."
    },
    {
      id: "SC76",
      name: "Saboteur Network",
      type: "SC1",
      category: "Hire Interaction",
      mechanicsType: "AO",
      mechanicsVariables: "Prevent all opponents' hires from being used next round",
      coopChange: -3,
      innovChange: -2,
      canBeHired: false,
      description: "Deploy saboteurs to disrupt all opponents' hires temporarily."
    },
    {
      id: "SC77",
      name: "Headhunter Firm",
      type: "SC1",
      category: "Hire Interaction",
      mechanicsType: "AO",
      mechanicsVariables: "Attempt to recruit any hire in play",
      coopChange: -2,
      innovChange: -1,
      canBeHired: false,
      description: "Use a professional firm to recruit a hire from another player."
    },
    {
      id: "SC78",
      name: "Bribery",
      type: "SC1",
      category: "Regulatory Action",
      mechanicsType: "AO",
      mechanicsVariables: "Reduce effectiveness of all other players' regulatory hires by 1",
      coopChange: -2,
      innovChange: -1,
      canBeHired: false,
      description: "Undermine opponents' regulatory hires, lessening their impact."
    },
    {
      id: "SC79",
      name: "Upgrade Facilities",
      type: "SC1",
      category: "Hire Upgrade",
      mechanicsType: "MM",
      mechanicsVariables: "Your hire's action no longer requires an Employee Pawn",
      coopChange: 0,
      innovChange: 1,
      canBeHired: false,
      description: "Improve facilities so your hire can act independently."
    },
    {
      id: "SC80",
      name: "Consultant Exchange Program",
      type: "SC1",
      category: "Alliance Building",
      mechanicsType: "MM",
      mechanicsVariables: "Swap hires with another player for one round",
      coopChange: 2,
      innovChange: 1,
      canBeHired: false,
      description: "Exchange hires temporarily to promote cooperation and share expertise."
    },
    {
      id: "SC81",
      name: "Technology License Agreement",
      type: "SC1",
      category: "Hire Interaction",
      mechanicsType: "MM",
      mechanicsVariables: "Use an opponent's hire action this round",
      coopChange: 1,
      innovChange: 1,
      canBeHired: false,
      description: "Negotiate access to an opponent's hire's action for mutual benefit."
    },
    {
      id: "SC82",
      name: "Assassination",
      type: "SC1",
      category: "Extreme Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Permanently remove a hire from the game",
      coopChange: -5,
      innovChange: -2,
      canBeHired: false,
      description: "Eliminate an opponent's hire entirely through drastic means."
    },
    {
      id: "SC83",
      name: "Employee Poaching",
      type: "SC1",
      category: "Hire Interaction",
      mechanicsType: "AO",
      mechanicsVariables: "Steal an Employee Pawn from another player for one round",
      coopChange: -2,
      innovChange: 0,
      canBeHired: false,
      description: "Temporarily lure away an Employee to join your company this round."
    },
    {
      id: "SC84",
      name: "Whistleblower",
      type: "SC1",
      category: "Hire Interaction",
      mechanicsType: "AO",
      mechanicsVariables: "Force an opponent to discard their hire due to exposure",
      coopChange: -1,
      innovChange: 1,
      canBeHired: false,
      description: "Expose misconduct, causing loss of an opponent's hire."
    },
    {
      id: "SC85",
      name: "Team Building Exercise",
      type: "SC1",
      category: "Hire Upgrade",
      mechanicsType: "MM",
      mechanicsVariables: "Increase your hire's effectiveness; gain additional benefits",
      coopChange: 1,
      innovChange: 0,
      canBeHired: false,
      description: "Improve teamwork to enhance your hire's action output."
    },
    {
      id: "SC86",
      name: "Corporate Espionage",
      type: "SC1",
      category: "Hire Interaction",
      mechanicsType: "AO",
      mechanicsVariables: "Copy an opponent's hire action this round",
      coopChange: -2,
      innovChange: -1,
      canBeHired: false,
      description: "Spy on an opponent's hire to replicate their action temporarily."
    },
    {
      id: "SC87",
      name: "Talent Scout",
      type: "SC1",
      category: "Hire Upgrade",
      mechanicsType: "MM",
      mechanicsVariables: "Replace your hire with a new one from your hand",
      coopChange: 0,
      innovChange: 1,
      canBeHired: false,
      description: "Recruit new talent to swap your current hire."
    },
    {
      id: "SC88",
      name: "Employee Sabotage",
      type: "SC1",
      category: "Hire Interaction",
      mechanicsType: "AO",
      mechanicsVariables: "Reduce an opponent's hire effectiveness",
      coopChange: -1,
      innovChange: -1,
      canBeHired: false,
      description: "Sabotage an opponent's hire, diminishing their effectiveness."
    },
    {
      id: "SC89",
      name: "Legal Action",
      type: "SC1",
      category: "Regulatory Action",
      mechanicsType: "AO",
      mechanicsVariables: "Prevent an opponent from using their hire next round",
      coopChange: -1,
      innovChange: 0,
      canBeHired: false,
      description: "File legal action to temporarily block an opponent's hire."
    },
    {
      id: "SC90",
      name: "Morale Boost",
      type: "SC1",
      category: "Hire Upgrade",
      mechanicsType: "RA",
      mechanicsVariables: "Gain an extra benefit when using your hire",
      coopChange: 1,
      innovChange: 0,
      canBeHired: false,
      description: "Increase morale to enhance your hire's output."
    },
    {
      id: "SC91",
      name: "Consultant Sabotage",
      type: "SC1",
      category: "Hire Interaction",
      mechanicsType: "AO",
      mechanicsVariables: "Negate an opponent's consultant action",
      coopChange: -1,
      innovChange: -1,
      canBeHired: false,
      description: "Sabotage an opponent's consultant, nullifying their immediate effect."
    },
    {
      id: "SC92",
      name: "Firewall Upgrade",
      type: "SC1",
      category: "Hire Protection",
      mechanicsType: "DN",
      mechanicsVariables: "Protect your hire from espionage",
      coopChange: 0,
      innovChange: 1,
      canBeHired: false,
      description: "Strengthen defenses against spying on your hire."
    },
    {
      id: "SC93",
      name: "Recruiting Drive",
      type: "SC1",
      category: "Hire Upgrade",
      mechanicsType: ["RA", "GA"],
      mechanicsVariables: "Gain a temporary Employee Pawn to use with your hire this round",
      coopChange: 0,
      innovChange: 1,
      canBeHired: false,
      description: "Expand workforce temporarily for more actions with your hire."
    },
    {
      id: "SC94",
      name: "Team Restructuring",
      type: "SC1",
      category: "Hire Upgrade",
      mechanicsType: "MM",
      mechanicsVariables: "Change your hire's category to any category",
      coopChange: 0,
      innovChange: 1,
      canBeHired: false,
      description: "Adjust your hire's focus to better suit your strategy."
    },
    {
      id: "SC95",
      name: "Market Research",
      type: "SC1",
      category: "Hire Interaction",
      mechanicsType: "PR",
      mechanicsVariables: "View all hires currently in play",
      coopChange: 0,
      innovChange: 1,
      canBeHired: false,
      description: "Gain insight into opponents' hires for strategic planning."
    }
  ],

  phase2StrategyCards: [
    {
      id: "P2C1",
      name: "Backdoor Negotiations",
      type: "P2C",
      category: "Alliance",
      mechanicsType: "MM",
      mechanicsVariables: "Form a temporary alliance with another player",
      coopChange: 2,
      innovChange: 1,
      coopRequirement: 0,
      innovRequirement: 0,
      description: "Form a strategic partnership with another player to oppose the Corporatio Supremo."
    },
    {
      id: "P2C2",
      name: "Quantum Sabotage",
      type: "P2C",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Add 2 Interference Cubes to the leader's board",
      coopChange: -3,
      innovChange: -2,
      coopRequirement: -3,
      innovRequirement: 0,
      description: "Risky sabotage action to cripple the leader's quantum system. High stakes with high reward."
    },
    {
      id: "P2C3",
      name: "Espionage Breakthrough",
      type: "P2C",
      category: "Research Enhancement",
      mechanicsType: "PR",
      mechanicsVariables: "Steal a random strategy card from the Corporatio Supremo",
      coopChange: 0,
      innovChange: 2,
      coopRequirement: 0,
      innovRequirement: 2,
      description: "Unlock critical knowledge by stealing a card from the leader. May reveal key information."
    },
    {
      id: "P2C4",
      name: "Joint Research Project",
      type: "P2C",
      category: "Alliance Building",
      mechanicsType: "MM",
      mechanicsVariables: "Share research benefits with another player",
      coopChange: 3,
      innovChange: 2,
      coopRequirement: 2,
      innovRequirement: 2,
      description: "Team up with another player to pool research efforts. Gains both players a strategic advantage."
    },
    {
      id: "P2C5",
      name: "Propaganda Campaign",
      type: "P2C",
      category: "Psychological Warfare",
      mechanicsType: "RA",
      mechanicsVariables: "Reduce the leader's Influence Points by 2",
      coopChange: 1,
      innovChange: -1,
      coopRequirement: 2,
      innovRequirement: 0,
      description: "Undermine the public image of the leader to sway public opinion."
    },
    {
      id: "P2C6",
      name: "Industrial Sabotage",
      type: "P2C",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Disable a key resource for the leader for one round",
      coopChange: -2,
      innovChange: -2,
      coopRequirement: -2,
      innovRequirement: 0,
      description: "Temporarily disable one of the leader's resources. Use sparingly for maximum effect."
    },
    {
      id: "P2C7",
      name: "Press Embargo",
      type: "P2C",
      category: "Regulatory Action",
      mechanicsType: "AO",
      mechanicsVariables: "Block the leader from playing any Influence cards next turn",
      coopChange: 0,
      innovChange: 0,
      coopRequirement: 0,
      innovRequirement: 0,
      description: "Impose a media embargo on the leader, cutting off their influence campaign."
    },
    {
      id: "P2C8",
      name: "Research Reversal",
      type: "P2C",
      category: "Sabotage",
      mechanicsType: "MM",
      mechanicsVariables: "Reverse one of the leader's technology advancements",
      coopChange: -2,
      innovChange: -3,
      coopRequirement: -3,
      innovRequirement: 3,
      description: "Sabotage the leader's technological breakthrough, causing significant setbacks."
    },
    {
      id: "P2C9",
      name: "Defector Recruitment",
      type: "P2C",
      category: "Alliance Building",
      mechanicsType: "AO",
      mechanicsVariables: "Recruit a defector from the leader's company",
      coopChange: 1,
      innovChange: 0,
      coopRequirement: -2,
      innovRequirement: 0,
      description: "Convince a key asset to defect to your side, gaining a pawn and reducing the leader's."
    },
    {
      id: "P2C10",
      name: "Targeted Assassination",
      type: "P2C",
      category: "Extreme Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Permanently remove a critical hire from the leader",
      coopChange: -5,
      innovChange: -2,
      coopRequirement: -4,
      innovRequirement: 0,
      description: "A high-risk maneuver to take out a vital player in the leader's team."
    },
    {
      id: "P2C11",
      name: "Network Disruption",
      type: "P2C",
      category: "Technological Warfare",
      mechanicsType: "AO",
      mechanicsVariables: "Disable the leader's communications for one turn",
      coopChange: -2,
      innovChange: -2,
      coopRequirement: 0,
      innovRequirement: 0,
      description: "Disrupt the leader's network infrastructure, limiting their communication and coordination."
    },
    {
      id: "P2C12",
      name: "Mutual Non-Aggression Pact",
      type: "P2C",
      category: "Alliance Building",
      mechanicsType: "MM",
      mechanicsVariables: "Form a pact with another player for the next two rounds",
      coopChange: 3,
      innovChange: 0,
      coopRequirement: 2,
      innovRequirement: 0,
      description: "Prevent aggression between you and another player for a short period, ensuring cooperation."
    },
    {
      id: "P2C13",
      name: "Scorched Earth",
      type: "P2C",
      category: "Extreme Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Destroy one technology advancement from all players",
      coopChange: -4,
      innovChange: -4,
      coopRequirement: -5,
      innovRequirement: -3,
      description: "An extreme act of technological destruction, setting everyone back to level the playing field."
    },
    {
      id: "P2C14",
      name: "Covert Operation",
      type: "P2C",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Temporarily disable the leader's quantum computer for one round",
      coopChange: -3,
      innovChange: -1,
      coopRequirement: -2,
      innovRequirement: 0,
      description: "Disable the leader's quantum computer, preventing any actions that involve quantum supremacy."
    },
    {
      id: "P2C15",
      name: "Political Pressure",
      type: "P2C",
      category: "Regulatory Action",
      mechanicsType: "RA",
      mechanicsVariables: "Reduce the leader's resource pool by 2",
      coopChange: 1,
      innovChange: -1,
      coopRequirement: 0,
      innovRequirement: 0,
      description: "Exert political pressure to reduce the resources available to the leader."
    },
    {
      id: "P2C16",
      name: "Headhunter Assault",
      type: "P2C",
      category: "Hire Interaction",
      mechanicsType: "AO",
      mechanicsVariables: "Steal a hire from the leader",
      coopChange: -2,
      innovChange: -1,
      coopRequirement: -3,
      innovRequirement: 0,
      description: "Aggressively recruit a key hire from the leader's company."
    },
    {
      id: "P2C17",
      name: "Influence Rebellion",
      type: "P2C",
      category: "Psychological Warfare",
      mechanicsType: "RA",
      mechanicsVariables: "Gain influence while reducing the leader's",
      coopChange: -1,
      innovChange: 2,
      coopRequirement: 0,
      innovRequirement: 3,
      description: "Position yourself as the new voice of influence, undermining the leader's control."
    },
    {
      id: "P2C18",
      name: "Quantum Poison",
      type: "P2C",
      category: "Extreme Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Add 3 Interference Cubes to the leader's quantum system",
      coopChange: -4,
      innovChange: -3,
      coopRequirement: -4,
      innovRequirement: 0,
      description: "Inject irreversible quantum errors into the leader's system, causing catastrophic failures."
    },
    {
      id: "P2C19",
      name: "Espionage Chain Reaction",
      type: "P2C",
      category: "Sabotage",
      mechanicsType: "PR",
      mechanicsVariables: "Peek at the leader's next three cards",
      coopChange: 0,
      innovChange: 2,
      coopRequirement: 0,
      innovRequirement: 2,
      description: "Reveal the leader's next moves, giving you insight into their strategy."
    },
    {
      id: "P2C20",
      name: "Trade Embargo",
      type: "P2C",
      category: "Regulatory Action",
      mechanicsType: "AO",
      mechanicsVariables: "Prevent the leader from using any resources for one round",
      coopChange: -1,
      innovChange: 0,
      coopRequirement: 0,
      innovRequirement: 0,
      description: "Enforce an embargo that blocks the leader's ability to gather or use resources."
    },
    {
      id: "P2C21",
      name: "False Flag Operation",
      type: "P2C",
      category: "Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Frame another player for a sabotage action",
      coopChange: -3,
      innovChange: -1,
      coopRequirement: -3,
      innovRequirement: 0,
      description: "Perform a sabotage action but shift the blame to another player, causing mistrust."
    },
    {
      id: "P2C22",
      name: "Global Hack",
      type: "P2C",
      category: "Extreme Action",
      mechanicsType: "AO",
      mechanicsVariables: "Force the leader to discard half their hand",
      coopChange: -3,
      innovChange: -2,
      coopRequirement: -4,
      innovRequirement: 2,
      description: "Initiate a global cyber attack that compromises the leader's strategic plans."
    },
    {
      id: "P2C23",
      name: "Data Corruption",
      type: "P2C",
      category: "Technological Warfare",
      mechanicsType: "AO",
      mechanicsVariables: "Corrupt the leader's data, preventing them from using qubit tokens next round",
      coopChange: -2,
      innovChange: -2,
      coopRequirement: 0,
      innovRequirement: 0,
      description: "Sabotage the leader's quantum data, causing systemic errors."
    },
    {
      id: "P2C24",
      name: "Misinformation Campaign",
      type: "P2C",
      category: "Psychological Warfare",
      mechanicsType: "RA",
      mechanicsVariables: "Reduce the leader's Innovation metric by 1 and gain an Influence Point",
      coopChange: 1,
      innovChange: -1,
      coopRequirement: 0,
      innovRequirement: 2,
      description: "Spread misinformation to slow the leader's innovation while boosting your own image."
    },
    {
      id: "P2C25",
      name: "Technological Coup",
      type: "P2C",
      category: "Extreme Sabotage",
      mechanicsType: "AO",
      mechanicsVariables: "Permanently disable one of the leader's key technology advancements",
      coopChange: -5,
      innovChange: -3,
      coopRequirement: -4,
      innovRequirement: 3,
      description: "Take down the leader's primary advancement, resetting their dominance."
    }
  ]
};